import type { FYPIdea } from "@/context/AppContext";

export function generateProjectProposal(idea: FYPIdea, userName: string, university: string): string {
  return `PROJECT PROPOSAL
${"=".repeat(60)}

Title: ${idea.title}
Student: ${userName}
University: ${university}
Submission Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

${"=".repeat(60)}

1. INTRODUCTION
${"-".repeat(40)}

${idea.overview}

This project aims to address a critical gap in the current landscape by leveraging ${idea.techStack.slice(0, 3).join(", ")} to build a robust, scalable solution.


2. PROBLEM STATEMENT
${"-".repeat(40)}

${idea.problemStatement}


3. OBJECTIVES
${"-".repeat(40)}

Primary Objectives:
  - Design and develop a functional prototype of ${idea.title}
  - Implement core features including ${idea.features.slice(0, 3).join(", ")}
  - Evaluate system performance against defined metrics
  - Document the development process and findings

Secondary Objectives:
  - Conduct user testing with a minimum of 10 participants
  - Achieve a System Usability Scale (SUS) score above 70
  - Publish findings in a conference paper (optional)


4. SCOPE
${"-".repeat(40)}

In Scope:
${idea.features.map((f) => `  - ${f}`).join("\n")}

Out of Scope:
  - Production deployment at enterprise scale
  - Integration with proprietary third-party systems
  - Multi-language localization (future work)


5. METHODOLOGY
${"-".repeat(40)}

This project will follow an Agile methodology with 2-week sprint cycles.

Phase 1 - Research & Analysis (Weeks 1-3):
  - Literature review of existing solutions
  - Requirements gathering through surveys and interviews
  - Technology evaluation and stack finalization

Phase 2 - System Design (Weeks 4-5):
  - System architecture design
  - Database schema design
  - UI/UX wireframing and prototyping
  - API specification

Phase 3 - Implementation (Weeks 6-12):
  - Sprint 1-2: Core backend development
  - Sprint 3-4: Frontend development
  - Sprint 5-6: Integration and feature completion

Phase 4 - Testing & Evaluation (Weeks 13-14):
  - Unit testing (target: >80% coverage)
  - Integration testing
  - User acceptance testing (UAT)
  - Performance benchmarking

Phase 5 - Documentation & Submission (Weeks 15-16):
  - Final report writing
  - Presentation preparation
  - Project demonstration


6. TECHNOLOGY STACK
${"-".repeat(40)}

${idea.techStack.map((t) => `  - ${t}`).join("\n")}

Justification:
This stack was selected for its industry adoption, community support, scalability, and alignment with the project requirements. ${idea.techStack[0]} provides the core processing capabilities while ${idea.techStack[1] || idea.techStack[0]} handles the user-facing interface.


7. EXPECTED OUTCOMES
${"-".repeat(40)}

${idea.potentialImpact}

Deliverables:
  - Working application with all MVP features
  - Source code repository with documentation
  - Final project report (minimum 10,000 words)
  - Presentation slides and demo video
  - User testing results and analysis


8. REFERENCES
${"-".repeat(40)}

${idea.literatureSummary}


${"=".repeat(60)}
Generated by FYP Forge - AI-Powered FYP Mentor
`;
}

export function generateLiteratureReview(idea: FYPIdea): string {
  return `LITERATURE REVIEW
${"=".repeat(60)}

Project: ${idea.title}
Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}

${"=".repeat(60)}

1. INTRODUCTION
${"-".repeat(40)}

This literature review examines existing research and solutions related to ${idea.title}. The review covers theoretical foundations, current approaches, identified gaps, and how this project positions itself within the existing body of knowledge.


2. BACKGROUND & CONTEXT
${"-".repeat(40)}

${idea.researchBackground}

The growing importance of this domain is evidenced by increasing academic publications and industry investments. The following sections analyze key contributions and identify research gaps that this project aims to address.


3. EXISTING SOLUTIONS & APPROACHES
${"-".repeat(40)}

3.1 Academic Research:
${idea.literatureSummary}

3.2 Industry Solutions:
Current commercial solutions in this space include various tools and platforms, each with their own strengths and limitations. However, most existing solutions face challenges related to:
  - Scalability in handling large-scale data
  - User experience and accessibility
  - Integration with existing workflows
  - Cost-effectiveness for educational institutions

3.3 Open-Source Alternatives:
The open-source community has contributed several relevant projects, though most are limited in scope or lack the comprehensive approach proposed in this project.


4. THEORETICAL FRAMEWORK
${"-".repeat(40)}

The project draws on several theoretical foundations:

  a) ${idea.techStack[0]}-based approaches for core processing
  b) Software engineering principles for system architecture
  c) Human-Computer Interaction (HCI) guidelines for interface design
  d) Agile methodology for project management

These frameworks provide a solid foundation for building a solution that is both technically sound and user-friendly.


5. RESEARCH GAP ANALYSIS
${"-".repeat(40)}

Despite significant progress in related areas, the following gaps remain:

  Gap 1: Limited integration between ${idea.features[0].toLowerCase()} and ${idea.features[1]?.toLowerCase() || "advanced analytics"}
  Gap 2: Insufficient focus on user experience in academic tools
  Gap 3: Lack of comprehensive, end-to-end solutions accessible to students
  Gap 4: Limited real-world evaluation with target user groups

This project addresses these gaps by proposing ${idea.title}, which combines multiple capabilities into a unified, user-centric platform.


6. COMPARATIVE ANALYSIS
${"-".repeat(40)}

| Criteria              | Existing Solutions | This Project       |
|----------------------|-------------------|--------------------|
| Core Functionality   | Partial           | Comprehensive      |
| User Experience      | Basic             | Modern, intuitive  |
| Scalability          | Limited           | Cloud-native       |
| Cost                 | Commercial/Paid   | Open-source        |
| Target Audience      | General           | Students/Academic  |
| Tech Stack Currency  | Mixed             | Modern (${idea.techStack.slice(0, 2).join(", ")}) |


7. CONCLUSION
${"-".repeat(40)}

The literature review reveals a clear opportunity for ${idea.title}. While existing solutions address parts of the problem, none provide a comprehensive, accessible, and modern solution tailored to the specific needs identified. This project builds upon established research while addressing the identified gaps through innovative use of ${idea.techStack.join(", ")}.


8. REFERENCES
${"-".repeat(40)}

${idea.literatureSummary}

Additional references should be gathered through systematic search of:
  - IEEE Xplore
  - ACM Digital Library
  - Google Scholar
  - arXiv preprints
  - Relevant conference proceedings


${"=".repeat(60)}
Generated by FYP Forge - AI-Powered FYP Mentor
`;
}

export function generateProgressReport(idea: FYPIdea, completedMilestones: string[]): string {
  const totalMilestones = 7;
  const progress = Math.round((completedMilestones.length / totalMilestones) * 100);
  
  return `PROGRESS REPORT
${"=".repeat(60)}

Project: ${idea.title}
Report Date: ${new Date().toLocaleDateString("en-US", { year: "numeric", month: "long", day: "numeric" })}
Overall Progress: ${progress}%

${"=".repeat(60)}

1. EXECUTIVE SUMMARY
${"-".repeat(40)}

This report presents the current progress on "${idea.title}". As of the report date, ${completedMilestones.length} out of ${totalMilestones} major milestones have been completed, representing ${progress}% overall progress.


2. COMPLETED MILESTONES
${"-".repeat(40)}

${completedMilestones.length > 0 
  ? completedMilestones.map((m, i) => `  ${i + 1}. [COMPLETED] ${m}`).join("\n")
  : "  No milestones completed yet. Project is in initial phase."}


3. CURRENT PHASE
${"-".repeat(40)}

${progress < 25 
  ? "The project is currently in the Research & Planning phase. Key activities include literature review, requirements gathering, and technology evaluation."
  : progress < 50 
    ? "The project is in the Design & Early Development phase. System architecture has been defined and initial implementation has begun."
    : progress < 75 
      ? "The project is in the Core Development phase. Major features are being implemented and integrated."
      : "The project is in the Testing & Finalization phase. Focus is on quality assurance, documentation, and presentation preparation."}


4. TECHNICAL PROGRESS
${"-".repeat(40)}

Technology Stack Implementation:
${idea.techStack.map((t) => `  - ${t}: ${progress > 30 ? "Configured and in use" : "Setup planned"}`).join("\n")}

Features Status:
${idea.features.map((f, i) => `  ${i + 1}. ${f} - ${i < completedMilestones.length ? "Completed" : i === completedMilestones.length ? "In Progress" : "Pending"}`).join("\n")}


5. CHALLENGES & MITIGATIONS
${"-".repeat(40)}

  Challenge 1: Complexity of ${idea.features[0]}
  Mitigation: Breaking down into smaller sub-tasks, seeking supervisor guidance

  Challenge 2: Data availability for testing
  Mitigation: Using synthetic data generation and public datasets

  Challenge 3: Time management with academic workload
  Mitigation: Strict sprint planning with buffer time built in


6. NEXT STEPS
${"-".repeat(40)}

Immediate priorities for the next reporting period:
  - Continue implementation of pending features
  - Begin integration testing
  - Prepare mid-project demonstration
  - Update documentation


7. TIMELINE ADHERENCE
${"-".repeat(40)}

${progress >= 40 
  ? "The project is on track with the planned timeline."
  : "The project needs acceleration to meet the planned timeline. Mitigation strategies are being implemented."}


${"=".repeat(60)}
Generated by FYP Forge - AI-Powered FYP Mentor
`;
}

export function generateFinalPresentation(idea: FYPIdea): string {
  return `FINAL PRESENTATION - SLIDE DECK OUTLINE
${"=".repeat(60)}

Project: ${idea.title}

${"=".repeat(60)}

SLIDE 1 - TITLE SLIDE
${"-".repeat(40)}
  Title: ${idea.title}
  Subtitle: Final Year Project Presentation
  Presented by: [Your Name]
  University: [University Name]
  Date: [Presentation Date]
  Supervisor: [Supervisor Name]


SLIDE 2 - AGENDA
${"-".repeat(40)}
  1. Problem Statement
  2. Literature Review
  3. Proposed Solution
  4. System Architecture
  5. Implementation
  6. Demo
  7. Testing & Results
  8. Conclusion & Future Work
  9. Q&A


SLIDE 3 - PROBLEM STATEMENT
${"-".repeat(40)}
  Key Problem:
  ${idea.problemStatement}

  Impact:
  - Who is affected and how
  - Current limitations of existing solutions
  - Why this matters now


SLIDE 4 - LITERATURE REVIEW
${"-".repeat(40)}
  ${idea.literatureSummary}

  Research Gap:
  - What existing solutions miss
  - How this project fills the gap


SLIDE 5 - PROPOSED SOLUTION
${"-".repeat(40)}
  ${idea.overview}

  Key Differentiators:
  - Unique approach or technology
  - Target audience focus
  - Comprehensive feature set


SLIDE 6 - SYSTEM ARCHITECTURE
${"-".repeat(40)}
  [Include system architecture diagram]
  
  Components:
  - Frontend: User interface layer
  - Backend: API and business logic
  - Database: Data storage and management
  - External Services: Third-party integrations

  Tech Stack: ${idea.techStack.join(", ")}


SLIDE 7 - KEY FEATURES
${"-".repeat(40)}
${idea.features.map((f, i) => `  Feature ${i + 1}: ${f}`).join("\n")}


SLIDE 8 - IMPLEMENTATION HIGHLIGHTS
${"-".repeat(40)}
  - Development methodology: Agile (2-week sprints)
  - Version control: Git with feature branching
  - Code quality: Linting, testing, code reviews
  - Key technical decisions and trade-offs


SLIDE 9 - LIVE DEMO
${"-".repeat(40)}
  [Live demonstration of the application]
  
  Demo Script:
  1. User registration and login
  2. Core feature walkthrough
  3. Results and output demonstration
  4. Edge cases handling


SLIDE 10 - TESTING & RESULTS
${"-".repeat(40)}
  Testing Approach:
  - Unit tests: [X]% coverage
  - Integration tests: All critical paths
  - User testing: [N] participants
  
  Results:
  - Performance metrics achieved
  - User satisfaction scores
  - Comparison with existing solutions


SLIDE 11 - CHALLENGES & LESSONS LEARNED
${"-".repeat(40)}
  Technical Challenges:
  - Challenge 1 and how it was resolved
  - Challenge 2 and the approach taken
  
  Lessons Learned:
  - Key takeaways from the development process
  - What you would do differently


SLIDE 12 - CONCLUSION & FUTURE WORK
${"-".repeat(40)}
  Achievements:
  - Successfully implemented ${idea.features.length} core features
  - Demonstrated feasibility of the approach
  - Positive user feedback received

  Future Work:
  - Feature enhancements
  - Scalability improvements
  - Potential for publication or commercialization


SLIDE 13 - THANK YOU & Q&A
${"-".repeat(40)}
  Thank you for your time and attention.
  
  Questions?
  
  Contact: [Your Email]
  Repository: [GitHub Link]


${"=".repeat(60)}
Presentation Tips:
- Keep each slide to 3-5 key points maximum
- Use visuals: diagrams, screenshots, charts
- Practice the demo multiple times
- Prepare for common viva questions
- Time target: 15-20 minutes + 10 minutes Q&A

Generated by FYP Forge - AI-Powered FYP Mentor
`;
}

export function generateFinalReport(idea: FYPIdea): string {
  return `FINAL REPORT - CHAPTER OUTLINE
${"=".repeat(60)}

Project: ${idea.title}

${"=".repeat(60)}

CHAPTER 1: INTRODUCTION (1,500 - 2,000 words)
${"-".repeat(40)}

1.1 Background
  ${idea.researchBackground}

1.2 Problem Statement
  ${idea.problemStatement}

1.3 Research Questions
  RQ1: How can ${idea.techStack[0]} be effectively utilized to address ${idea.features[0].toLowerCase()}?
  RQ2: What is the optimal architecture for integrating ${idea.features.slice(0, 3).join(", ")}?
  RQ3: How does the proposed solution compare to existing approaches in terms of performance and usability?

1.4 Objectives
  - Design and implement a functional prototype
  - Evaluate against defined performance metrics
  - Conduct user testing and gather feedback
  - Document findings and contribute to knowledge

1.5 Scope and Limitations
  In Scope: ${idea.features.join(", ")}
  Limitations: Single-institution testing, limited dataset size

1.6 Report Structure
  Overview of each chapter and its contents


CHAPTER 2: LITERATURE REVIEW (2,500 - 3,000 words)
${"-".repeat(40)}

2.1 Theoretical Background
  ${idea.researchBackground}

2.2 Related Work
  ${idea.literatureSummary}

2.3 Technology Review
  Analysis of: ${idea.techStack.join(", ")}

2.4 Comparative Analysis of Existing Solutions
  Table comparing features, performance, limitations

2.5 Research Gap
  Identified gaps and how this project addresses them

2.6 Summary
  Key findings from the literature


CHAPTER 3: METHODOLOGY (1,500 - 2,000 words)
${"-".repeat(40)}

3.1 Research Methodology
  Mixed-methods approach combining development with evaluation

3.2 Development Methodology
  Agile with 2-week sprints, iterative prototyping

3.3 Data Collection Methods
  Surveys, interviews, usage analytics, testing data

3.4 Evaluation Framework
  Performance metrics, usability scales, comparative benchmarks

3.5 Tools and Technologies
  ${idea.techStack.map((t) => `- ${t}: Purpose and justification`).join("\n  ")}

3.6 Ethical Considerations
  Data privacy, informed consent, responsible AI use


CHAPTER 4: SYSTEM DESIGN (2,000 - 2,500 words)
${"-".repeat(40)}

4.1 System Architecture
  High-level architecture diagram and description

4.2 Database Design
  ER diagrams, schema design, normalization

4.3 API Design
  Endpoint specifications, authentication flow

4.4 User Interface Design
  Wireframes, user flow diagrams, design decisions

4.5 Security Design
  Authentication, authorization, data protection

4.6 Deployment Architecture
  Cloud infrastructure, CI/CD pipeline


CHAPTER 5: IMPLEMENTATION (2,000 - 2,500 words)
${"-".repeat(40)}

5.1 Development Environment Setup
  Tools, IDEs, version control

5.2 Core Feature Implementation
${idea.features.map((f, i) => `  5.2.${i + 1} ${f}\n    - Technical approach\n    - Key code snippets\n    - Challenges and solutions`).join("\n")}

5.3 Integration and Testing During Development
  Continuous integration, automated testing

5.4 Deployment
  Steps, configuration, environment management


CHAPTER 6: TESTING & EVALUATION (1,500 - 2,000 words)
${"-".repeat(40)}

6.1 Testing Strategy
  Unit, integration, system, and acceptance testing

6.2 Test Results
  Coverage reports, test outcomes

6.3 Performance Evaluation
  Response times, throughput, resource usage

6.4 User Evaluation
  SUS scores, task completion rates, feedback analysis

6.5 Comparative Evaluation
  Comparison with existing solutions

6.6 Discussion of Results
  Interpretation and implications


CHAPTER 7: CONCLUSION (1,000 - 1,500 words)
${"-".repeat(40)}

7.1 Summary of Achievements
  Features completed, objectives met

7.2 Contributions
  Technical and knowledge contributions

7.3 Limitations
  Constraints and boundaries of the work

7.4 Future Work
  Potential improvements and extensions

7.5 Personal Reflection
  Learning outcomes and growth


APPENDICES
${"-".repeat(40)}

A. User Survey Questionnaire
B. Test Cases and Results
C. API Documentation
D. Database Schema (Full)
E. User Manual
F. Source Code Repository Link


REFERENCES
${"-".repeat(40)}

${idea.literatureSummary}

[Include minimum 20 references in IEEE or APA format]


${"=".repeat(60)}
Writing Tips:
- Total word count target: 10,000 - 15,000 words
- Use academic writing style (third person, formal)
- Include figures, tables, and code snippets
- Cite all sources properly
- Proofread for grammar and consistency

Generated by FYP Forge - AI-Powered FYP Mentor
`;
}
