import { useNavigate } from "react-router-dom";
import { ArrowLeft, BookOpen, Target, Lightbulb, FileText, ArrowRight } from "lucide-react";

const sections = [
  {
    icon: Target,
    title: "Problem Statement",
    content: "Academic plagiarism remains a significant challenge in higher education, with existing tools often failing to detect paraphrased content and cross-language plagiarism. There is a need for intelligent detection systems that go beyond simple string matching.",
    color: "bg-pastel-purple",
  },
  {
    icon: BookOpen,
    title: "Research Background",
    content: "Natural Language Processing has advanced significantly with transformer architectures (BERT, GPT). These models can understand semantic meaning, enabling more sophisticated plagiarism detection beyond n-gram matching used by traditional tools like Turnitin.",
    color: "bg-pastel-blue",
  },
  {
    icon: Lightbulb,
    title: "Potential Impact",
    content: "An AI-powered plagiarism detector could significantly improve academic integrity enforcement, reduce manual review time by 70%, and provide more accurate detection of paraphrased and translated content.",
    color: "bg-pastel-green",
  },
  {
    icon: FileText,
    title: "Literature Summary",
    content: "Key papers: (1) Foltýnek et al. (2019) - Taxonomy of plagiarism detection methods, (2) Wahle et al. (2022) - Transformer-based plagiarism detection, (3) Alzahrani et al. (2012) - Understanding plagiarism linguistic patterns.",
    color: "bg-pastel-yellow",
  },
];

export default function Research() {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen gradient-soft pb-8">
      <div className="px-6 pt-8 pb-4 flex items-center gap-3">
        <button onClick={() => navigate(-1)} className="w-10 h-10 rounded-2xl bg-card shadow-soft flex items-center justify-center">
          <ArrowLeft className="w-4 h-4" />
        </button>
        <div className="flex-1">
          <h1 className="text-lg font-bold">AI Research Insights</h1>
          <p className="text-xs text-muted-foreground">Generated by Forge AI</p>
        </div>
      </div>

      <div className="px-6 space-y-4">
        {sections.map((section, i) => (
          <div
            key={section.title}
            className="bg-card rounded-3xl p-5 shadow-card animate-slide-up"
            style={{ animationDelay: `${i * 0.1}s` }}
          >
            <div className="flex items-center gap-3 mb-3">
              <div className={`w-10 h-10 ${section.color} rounded-2xl flex items-center justify-center`}>
                <section.icon className="w-5 h-5 text-primary" />
              </div>
              <h3 className="text-sm font-bold">{section.title}</h3>
            </div>
            <p className="text-xs text-muted-foreground leading-relaxed">{section.content}</p>
          </div>
        ))}

        <button
          onClick={() => navigate("/roadmap")}
          className="w-full gradient-accent text-primary-foreground py-3.5 rounded-2xl font-semibold text-sm flex items-center justify-center gap-2 shadow-soft mt-4"
        >
          View Project Roadmap <ArrowRight className="w-4 h-4" />
        </button>
      </div>
    </div>
  );
}
